#!/bin/zsh

function usage() {
    echo "Usage: uvv [-p|--python VERSION] SCRIPT_PATH"
    return 0
}

typeset -A opts
zparseopts -D -E -F -M -A opts - h -help=h p: -python:=p

if ((${+opts[-h]})); then
    usage
    return 1
fi

if [[ ${#@} -ne 1 ]]; then
    usage
    return 1
fi

typeset -a python_args
((${+opts[-p]})) && python_args+=("--python" "${opts[-p]#=}")

uv venv "${python_args[@]}" --clear
uv export --script $1 | uv pip sync -
