# Reload config without restarting tmux
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Prefix key
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

set -g @tpm-install "i"          # Change the install binding to lowercase 'i'
set -g renumber-windows on       # Renumber windows when one is closed
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g history-limit 1000000     # increase history size (from 2,000)
set -g set-clipboard on          # use system clipboard
set -g default-terminal "${TERM}"
# setw -g mode-keys vi             # Vimish motions

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

# Divider colors
set -g pane-border-style 'fg=#BD93F9,bg=default'
set -g pane-active-border-style 'fg=#BD93F9,bg=default'

# Split panes using | and - (more intuitive than % and ")
bind h split-window -v
bind v split-window -h
unbind '"'
unbind %

# disable delete pane confirmation
unbind x
bind x kill-pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'dracula/tmux'

set -g status-position top
set -g @dracula-plugins 'git'
# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
set -g @dracula-show-left-icon "🧛‍♂️|#S"
# set -g @dracula-clients-minimum 1
set -g @dracula-git-show-current-symbol ✓
set -g @dracula-git-show-repo-name true
# set -g @dracula-git-disable-status false
# set -g @dracula-git-no-untracked-files true
# set -g @dracula-show-timezone true
# set -g @dracula-show-location false
set -g @dracula-border-contrast true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
